# Generated by Django 4.1.1 on 2022-09-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('agent', 'Agent'), ('vendor', 'Vendor'), ('customer', 'Customer')], max_length=25),
        ),
    ]
