# Generated by Django 4.1.1 on 2022-09-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_phone_alter_account_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
