# Generated by Django 4.1.1 on 2022-09-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('staff', 'Staff'), ('vendor', 'Vendor'), ('customer', 'Customer')], max_length=25),
        ),
    ]
