# Generated by Django 4.1.1 on 2022-09-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=25)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash On Delivery'), ('op', 'Online Payment')], default=None, max_length=25, null=True)),
            ],
        ),
    ]
