# Generated by Django 4.1.1 on 2022-09-17 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_vendor_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.address'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.address'),
        ),
    ]
