# Generated by Django 4.1.1 on 2022-09-20 12:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_customer_address_alter_vendor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Dhaka', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.CharField(default='Dhaka', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone1',
            field=phonenumber_field.modelfields.PhoneNumberField(default='01742714066', max_length=128, region='BD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BD'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(default='Dhaka', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='district',
            field=models.CharField(default='Dhaka', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone1',
            field=phonenumber_field.modelfields.PhoneNumberField(default='01742714066', max_length=128, region='BD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BD'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
