# Generated by Django 4.1.1 on 2022-09-30 21:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_invoice_alter_vendor_nid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone1',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='BD'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='district',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='nid',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='phone1',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='BD'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='district',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone1',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='BD'),
        ),
    ]
