# Generated by Django 4.1.1 on 2022-09-30 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_address_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.DateField(null=True)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('isReturned', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='store.deliveryagent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
    ]
