# Generated by Django 4.1.1 on 2022-09-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderlogg_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderLogg',
            new_name='Order',
        ),
    ]
