# Generated by Django 4.1.1 on 2022-09-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_orderlogg_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Basket',
        ),
        migrations.RenameModel(
            old_name='CartItem',
            new_name='BasketItem',
        ),
        migrations.RenameField(
            model_name='basketitem',
            old_name='cart',
            new_name='basket',
        ),
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together={('basket', 'product')},
        ),
    ]
