# Generated by Django 4.1.1 on 2022-09-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_cart_basket_rename_cartitem_basketitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='unit_price',
            new_name='total_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('op', 'Online Payment')], default=None, max_length=25),
        ),
    ]
