# Generated by Django 4.1.1 on 2022-10-05 04:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_coupon_productsonpromotion_promotype_promotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsOnPromotionalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_override', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_on_promotional_offer_product', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('offer_start', models.DateField()),
                ('offer_end', models.DateField()),
                ('promo_reduction', models.IntegerField(default=0)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotional_offer_coupon', to='store.coupon')),
                ('products', models.ManyToManyField(related_name='promotional_offer_products', through='store.ProductsOnPromotionalOffer', to='store.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='products',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='promo_type',
        ),
        migrations.RenameModel(
            old_name='PromoType',
            new_name='PromotionType',
        ),
        migrations.DeleteModel(
            name='ProductsOnPromotion',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.AddField(
            model_name='promotionaloffer',
            name='promo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotional_offer_promo_type', to='store.promotiontype'),
        ),
        migrations.AddField(
            model_name='productsonpromotionaloffer',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_on_promotional_offer_promotion', to='store.promotionaloffer'),
        ),
        migrations.AlterUniqueTogether(
            name='productsonpromotionaloffer',
            unique_together={('product', 'promotion')},
        ),
    ]
