# Generated by Django 4.1.1 on 2022-10-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productsonpromotionaloffer_promotionaloffer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionaloffer',
            name='promo_reduction',
            field=models.FloatField(default=0),
        ),
    ]
