# Generated by Django 4.1.1 on 2022-09-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_unit_price_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('op', 'Online Payment')], default=None, max_length=25, null=True),
        ),
    ]
