# Generated by Django 4.1.2 on 2022-10-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_promotionaloffer_promo_reduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(default='images.png', upload_to='photos/products/featured/'),
        ),
    ]
