# Generated by Django 4.1.2 on 2022-10-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_productvariation_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='image',
            field=models.ImageField(default='images.png', upload_to='photos/products/variations/'),
        ),
    ]
